version: '3.4'

services:

  app:
    image: python:3.9.4
    container_name: app
    hostname: app
    networks:
      - perf
    restart: no
    volumes:
        - type: bind
          source: ./app
          target: /app
    command: bash -c "pip3 install redis && python /app/app.py"
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    hostname: redis
    networks:
      - perf

  # postgres:
  #   image: postgres:12-alpine
  #   container_name: postgres
  #   hostname: postgres
  #   restart: always
  #   networks:
  #     - merkle
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=pm
  #     - POSTGRES_PASSWORD=supersecret!

networks:
  merkle:
    external: false

# volumes:
#   postgres:
