version: '3.4'

services:

  app:
    image: python:3.9.4-alpine
    container_name: app
    hostname: app
    networks:
      - perf
    restart: "no"
    volumes:
        - type: bind
          source: ./app
          target: /app
    command: sh -c "pip3 install redis && sleep 5 && python /app/app.py"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    hostname: redis
    networks:
      - perf

networks:
  perf:
